### ISSUE TITLE
ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by androane** [thornomad/django-hitcount#64]
When my model has a pk that is a string, the call `hit_count = HitCount.objects.get_for_object(obj)` fails with `invalid literal for int() with base 10: 'blablabla'`

I suppose django hit count is not adapted to strings

**Comment by thornomad** [comment]
Yea - I believe it’s locked into a integer primary key for the generic
relation at this point. I’m not sure if that was the only way to do it back
in the day or I just set it up that way knowingly but it’s still that way
now. You could fork it and change the generic relation setup to a TextField
and that should fix it.

**Comment by androane** [comment]
@thornomad Thanks for your reply.

I tried that but it seems that it's still not working. Something is breaking, not sure what...

**Comment by karinakozarova** [comment]
I had the same problem. I wrote `{% get_hit_count for [event] within [days=1] %}`. However it should be `{% get_hit_count for event within days=1 %}`

**Comment by bashu** [comment]
@thornomad this one must be fixed (it was my mistake after all)

**Comment by macher91** [comment]
Hi,
I don't won't create new issue but last version is not resolving problem correctly.
PostgreSQL is "strongly typed", that's why I have errors:

>  No operator matches the given name and argument type(s). You might need to add explicit type casts.

**Comment by joshgeller** [comment]
We are having the same problem with Postgres after upgrading to `1.3.1`.

**Comment by bashu** [comment]
@macher91 @joshgeller can you try this:
```sql
create function pg_catalog.text(int) returns text immutable language sql as $$select textin(int4out($1))$$;
create cast (int as text) with function pg_catalog.text(int) as implicit;
```
